apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app-backend-02
          image: rishu89/fullstack:backend_02
          ports:
            - containerPort: 4000

        - name: node-app-frontend-02
          image: rishu89/fullstack:frontend_02
          ports:
            - containerPort: 5173  # frontend should be on 5173 

        - name: node-app-db
          image: mongo:4.4.18
          ports:
            - containerPort: 27017
---

apiVersion: v1
kind: Service
metadata:
  name: service-example
spec:
  selector:
    app: node-app
  ports:
    - name: http
      port: 8080
      targetPort: 5173  # forward to frontend container
  type: LoadBalancer
